version: '3.8'
services:
  # Express app container
  app:
    build:
      context: ./backend
    command: sh -c "npm run dev"
    ports:
      - '5000:5000' # Map port 5000 of the container to port 5000 of the host
    environment:
      - MONGO_URI=mongodb://mongo:27017/apartmentDB # MongoDB connection string pointing to 'mongo' service
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    depends_on:
      - mongo # Ensure MongoDB starts first
  mongo:
    image: 'mongo:latest'
    command: ['mongod', '--quiet']
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
