version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    environment:
      - API_URL=http://backend:5000
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./shared:/shared
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/apartmentDB
      - FRONT_APP=http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./shared:/shared
    depends_on:
      - mongo

  mongo:
    image: 'mongo:latest'
    command: ['mongod', '--quiet']
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
networks:
  app-network:
    driver: bridge
